// <auto-generated />
using System;
using CarShopManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarShopManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarShopManagementSystem.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("CarShopManagementSystem.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Costing")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EstimatedPriceMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EstimatedPriceMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<int?>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("SoldDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubBrandId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("SubBrandId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarShopManagementSystem.Models.CreditCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CVV")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("ExpiryMonth")
                        .HasColumnType("int");

                    b.Property<int>("ExpiryYear")
                        .HasColumnType("int");

                    b.Property<string>("HolderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("CreditCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 50000m,
                            CVV = "123",
                            CardNumber = "4111111111111111",
                            ExpiryMonth = 12,
                            ExpiryYear = 2027,
                            HolderName = "John Doe",
                            IsValid = true
                        },
                        new
                        {
                            Id = 2,
                            Balance = 45000m,
                            CVV = "456",
                            CardNumber = "5500000000000004",
                            ExpiryMonth = 11,
                            ExpiryYear = 2028,
                            HolderName = "Jane Smith",
                            IsValid = true
                        },
                        new
                        {
                            Id = 3,
                            Balance = 60000m,
                            CVV = "789",
                            CardNumber = "340000000000009",
                            ExpiryMonth = 10,
                            ExpiryYear = 2029,
                            HolderName = "Ali Ahmad",
                            IsValid = true
                        },
                        new
                        {
                            Id = 4,
                            Balance = 10000m,
                            CVV = "012",
                            CardNumber = "30000000000004",
                            ExpiryMonth = 9,
                            ExpiryYear = 2026,
                            HolderName = "Sara Ibrahim",
                            IsValid = true
                        },
                        new
                        {
                            Id = 5,
                            Balance = 8000m,
                            CVV = "345",
                            CardNumber = "6011000000000004",
                            ExpiryMonth = 8,
                            ExpiryYear = 2030,
                            HolderName = "Mohamed Ali",
                            IsValid = true
                        },
                        new
                        {
                            Id = 6,
                            Balance = 12000m,
                            CVV = "678",
                            CardNumber = "3530111333300000",
                            ExpiryMonth = 7,
                            ExpiryYear = 2027,
                            HolderName = "Lina Hassan",
                            IsValid = true
                        },
                        new
                        {
                            Id = 7,
                            Balance = 30000m,
                            CVV = "901",
                            CardNumber = "6331101999990016",
                            ExpiryMonth = 6,
                            ExpiryYear = 2028,
                            HolderName = "Omar Saleh",
                            IsValid = true
                        },
                        new
                        {
                            Id = 8,
                            Balance = 15000m,
                            CVV = "234",
                            CardNumber = "6759649826438453",
                            ExpiryMonth = 5,
                            ExpiryYear = 2029,
                            HolderName = "Rania Khaled",
                            IsValid = true
                        },
                        new
                        {
                            Id = 9,
                            Balance = 20000m,
                            CVV = "567",
                            CardNumber = "4111111111111129",
                            ExpiryMonth = 4,
                            ExpiryYear = 2027,
                            HolderName = "Invalid Card",
                            IsValid = false
                        },
                        new
                        {
                            Id = 10,
                            Balance = 0m,
                            CVV = "890",
                            CardNumber = "5500000000000051",
                            ExpiryMonth = 3,
                            ExpiryYear = 2027,
                            HolderName = "No Funds",
                            IsValid = true
                        });
                });

            modelBuilder.Entity("CarShopManagementSystem.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("CarShopManagementSystem.Models.SubBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("SubBrands");
                });

            modelBuilder.Entity("CarShopManagementSystem.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CarShopManagementSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@carshop.com",
                            FirstName = "Admin",
                            IsAdmin = true,
                            LastName = "User",
                            Password = "Admin123!",
                            RegisterDate = new DateTime(2025, 9, 4, 0, 5, 48, 303, DateTimeKind.Local).AddTicks(5405),
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("CarShopManagementSystem.Models.Booking", b =>
                {
                    b.HasOne("CarShopManagementSystem.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarShopManagementSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarShopManagementSystem.Models.Car", b =>
                {
                    b.HasOne("CarShopManagementSystem.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.HasOne("CarShopManagementSystem.Models.SubBrand", "SubBrand")
                        .WithMany()
                        .HasForeignKey("SubBrandId");

                    b.Navigation("Manufacturer");

                    b.Navigation("SubBrand");
                });

            modelBuilder.Entity("CarShopManagementSystem.Models.SubBrand", b =>
                {
                    b.HasOne("CarShopManagementSystem.Models.Manufacturer", "Manufacturer")
                        .WithMany("SubBrands")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("CarShopManagementSystem.Models.Transaction", b =>
                {
                    b.HasOne("CarShopManagementSystem.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarShopManagementSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarShopManagementSystem.Models.Manufacturer", b =>
                {
                    b.Navigation("SubBrands");
                });
#pragma warning restore 612, 618
        }
    }
}
